### ISSUE TITLE
User Story - 2

### ISSUE THREAD

**Issue by traylor1** [theworkingmen/majorpotential#23]
As a high school student seeking to take advantage of in-state tuition, I want to know what colleges in the cities around me offer the major I want to study.

**Comment by abelhtt** [comment]
As part of the project, we are adding links to universities within a given city. This will be implemented in the sample static pages of phase 1. 
Time estimation: 4 hours
Assumptions: We can scrape the data from our sources.

**Comment by abelhtt** [comment]
@traylor1 What is the actual time it took for the implementation?

**Comment by traylor1** [comment]
Depends on what all is considered a part of this story. Creating the base pages, no CSS, but with links between cities to respective universities, around 2.5 hours, maybe a little less. Styling it and all the other pages made it take longer, a collective 12 or so hours between me and Sup, more or less.

**Comment by abelhtt** [comment]
Ok Great!
